name: Keep Alive

on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:  # 👈 This enables the "Run workflow" button

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    steps:
      - name: Ping site
        run: curl -I https://zexc2.github.io/OKX-EMA-5-bot-real/
